### ISSUE TITLE
Mac App and sketch plugin not working

### ISSUE THREAD

**Issue by tiagomaricate** [Iconscout/iconscout-app#1]
Hi people,
After the last update, the Mac app is not working.
When I try to click on LOGIN button, nothing happens.
The same for the Sketch plugin.
Could check this? Looks like an often bug.
My last e-mail was about the plugin bug.
Now the app has the same problem.
I also wrote to the support e-mail.

**Comment by tarunmangukiya** [comment]
Hi @tiagomaricate, which OS are you on? I just checked it with my device and it's opening the login link in web.

Can you try restarting the App (Cmd + Q) or MacBook? I'll be happy to get on call to resolve this issue.

**Comment by tiagomaricate** [comment]
> Hi @tiagomaricate, which OS are you on? I just checked it with my device and it's opening the login link in web.
> 
> Can you try restarting the App (Cmd + Q) or MacBook? I'll be happy to get on call to resolve this issue.

I'm using BigSUr 11.1
I tried to restart and reinstall the plugin and the app and the problem persist.

**Comment by tiagomaricate** [comment]
I managed to put the app back to work but the plugin still buggy.
I press the login button and it starts a loading. And nothing else.

**Comment by tarunmangukiya** [comment]
[artifacts-2.zip](https://github.com/Iconscout/iconscout-app/files/5749825/artifacts-2.zip)

Can you try this for Sketch?

**Comment by tarunmangukiya** [comment]
Hi @tiagomaricate,

We've fixed the plugin and released it. You can download it from https://iconscout.com/icondrop/for-sketch
